# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"
  - nodejs_version: "7"
  - nodejs_version: "8"

# Install scripts. (runs after cloning)
install:
  # Get the latest version of Node.js
  - ps: Install-Product node $env:nodejs_version
  #install modules
  - npm install

# Post-install test scripts.
test_scripts:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run test
  - npm test

# Don't actually build
  build: off
